const fs = require('fs')
const { saveOrUpdateSongToDb } = require('./saveToDB')

const readSongFile = (i) => {
  try {
    const d = new Date(2021, 5, 23)
    d.setDate(d.getDate() + i)
    const date = `${d.getDate()}-${d.getMonth()}-${d.getFullYear()}`
    const file = fs.readFileSync(`../data/songs-${date}.json`)
    const parsed = JSON.parse(file)
    return parsed
  } catch {
    return null
  }
}

const goTroughOld = async () => {
  let i = 0
  const songs = []
  while (true) {
    const songsFromFile = readSongFile(i)
    if (!songsFromFile) {
      break
    }
    songs.push(...songsFromFile)
    i++
  }
  let succesfulCount = 0
  for (let song of songs) {
    song.notePages = song.notePages.map(({ notes, ...otherNotePageFields }) => ({
      notes: notes.map(({ note, ...otherNoteFields }) => ({
        note: note >= 12 ? note - Math.floor(note / 12) * 12 : note,
        ...otherNoteFields,
      })),
      ...otherNotePageFields,
    }))
    if (!song.language) {
      song.language = 'English'
    }
    if (!song.gap) {
      song.gap = 0
    }
    song.gapIsAutoGenerated = true
    const res = await saveOrUpdateSongToDb(song)
    if (res.errors) {
      console.log(res.errors)
    }
    if (res.data) {
      succesfulCount++
      success = true
    }
  }
  console.log('Saved/updated', succesfulCount, 'of', songs.length, 'songs to DB')
}

goTroughOld()
