export interface Octave {
  min: number
  max: number
  octave: number
  trueMax: number
  octaveNotes: OctaveNote[]
}

export interface Player {
  isEnabled: boolean
  currentlySungNote: CurrentlySungNote | null
}

export interface CurrentlySungNote {
  frequency: number
  key: string
  octave: number
}

export interface OctaveNote {
  name: string
  freq: number
}

export interface Dimensions {
  height: number
  width: number
}

export interface Note {
  name: string
  currentBeat: number
}

export interface SungNote {
  name: string | undefined
  wholeBeat: number
}

export interface Song {
  _id: number
  title: string
  artist: string
  language: string
  year?: number
  bpm: number
  gap: number
  goldenNotes: boolean
  createdBy: string
  views: number
  rating: number
  ratingCount: number
  notePages: NotePage[]
  gapIsAutoGenerated: boolean
  videoId?: string
  alternativeVideoIds?: string
}

export interface NotePageNote {
  type: 'normal' | 'golden' | 'free'
  beat: number
  length: number
  note: number
  lyric: string
  isSecondOctave: boolean
}

export interface NotePage {
  startBeat: number
  endBeat: number
  notes: NotePageNote[]
}

export interface ScoreInfo {
  score: number
  hitNotes: number
  missedNotes: number
  scorePerNote: number
  addedAmount?: number
  percentageOnPage?: number
}
