export interface Octave {
  min: number
  max: number
  octave: number
  trueMax: number
  octaveNotes: OctaveNote[]
}

export interface NoteGroup {
  timestamp: number
  notes: CurrentlySungNote[]
}

export interface Player {
  isEnabled: boolean
  sungNotes: NoteGroup[]
  clearSungNotes: Function
  handleAudioProcessTick: Function
}

export interface CurrentlySungNote {
  frequency: number
  key: string
  octave: number
}

export interface OctaveNote {
  name: string
  freq: number
}

export interface Dimensions {
  height: number
  width: number
}

export interface Note {
  name: string
  currentBeat: number
}

export interface SungNote {
  name: string | undefined
  beat: number
}

export interface Tuner {
  pitch: number
  noteName: string
  updatePitch: Function
  stopUpdatingPitch: Function
  add: Function
  play: Function
  isEnabled?: boolean
}

export interface Song {
  _id: number
  title: string
  artist: string
  language: string
  year?: number
  bpm: number
  gap: number
  goldenNotes: boolean
  createdBy: string
  views: number
  rating: number
  ratingCount: number
  notePages: NotePage[]
  gapIsAutoGenerated: boolean
  videoId?: string
  alternativeVideoIds?: string
  genres?: string[]
  styles?: string[]
  smallImage?: string
  bigImage?: string
}

export interface NotePageNote {
  type: 'normal' | 'golden' | 'free'
  beat: number
  length: number
  note: number
  lyric: string
  isSecondOctave: boolean
}

export interface NotePage {
  startBeat: number
  endBeat: number
  notes: NotePageNote[]
}

export interface ScoreInfo {
  score: number
  hitNotes: number
  missedNotes: number
  scorePerNote: number
  calculatedNotePageIndexes: number[]
  addedAmount?: number
  percentageOnPage?: number
}

export interface PlayerSettings {
  deviceId: string
  difficulty: 'Expert' | 'Hard' | 'Normal' | 'Easy' | 'Auto-Play'
}

export interface Settings {
  playerSettings: PlayerSettings[]
}
