import { Max, Min } from 'class-validator'
import { Field, InputType, Int } from 'type-graphql'

@InputType()
export class NotePageNoteInput {
  @Field()
  beat: number

  @Field()
  type: string

  @Field()
  length: number

  @Field()
  @Min(0)
  @Max(11)
  note: number

  @Field()
  noteName: string

  @Field()
  lyric: string

  @Field()
  isSecondOctave: boolean
}

@InputType()
export class NotePageInput {
  @Field()
  startBeat: number

  @Field()
  endBeat: number

  @Field(() => [NotePageNoteInput])
  notes: NotePageNoteInput[]
}

@InputType()
export class NewSongInput {
  @Field()
  title: string

  @Field()
  artist: string

  @Field()
  language?: string

  @Field(() => Int, { nullable: true })
  year?: number

  @Field({ nullable: true })
  edition?: string

  @Field(() => [String], { nullable: true })
  genres: string[]

  @Field(() => [String], { nullable: true })
  styles?: string[]

  @Field({ nullable: true })
  smallImage?: string

  @Field({ nullable: true })
  bigImage?: string

  @Field()
  bpm: number

  @Field()
  gap: number

  @Field()
  goldenNotes: boolean

  @Field()
  createdBy: string

  @Field()
  views: number

  @Field()
  rating: number

  @Field()
  ratingCount: number

  @Field(() => [NotePageInput])
  notePages: NotePageInput[]

  @Field()
  gapIsAutoGenerated: boolean

  @Field({ nullable: true })
  videoId?: string

  @Field(() => [String], { nullable: true })
  alternativeVideoIds?: string[]
}
